title: "My MD Blog"
description: "Markdown notes and docs"
theme: jekyll-theme-minimal
baseurl: "/blog"
url: "https://gks930620.github.io"
lang: "ko"
markdown: kramdown
repository_url: "https://github.com/gks930620/blog"
home_label: "메인으로"
show_downloads: false
defaults:
  - scope:
      path: ""
    values:
      layout: default
